version: '3'
services:
    db:
        build:
            context: ./dockerfiles/awesome-postgres
        expose:
            - "5432"
        environment:
            PGDATA: "/code-or-die/db/"
            POSTGRES_DB: "code-or-die"
            POSTGRES_LOGFILE: "/var/log/code-or-die.db.log"
            POSTGRES_INITDB_ARGS: "-D /code-or-die/db/"
        healthcheck:
            test: ["CMD", "postgres", "-c", "'CREATE EXTENSION plpython3u;'", "-U", "postgres", "code-or-die"]
            interval: 15s
            timeout: 10s
            retries: 3
    cod:
        # restart: always
        build: 
            context: ./code-or-die/
        depends_on:
            - db
